/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package anggaranapp;

import javax.swing.JOptionPane;

/**
 *
 * @author my
 */
public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        tripData = new javax.swing.JMenuItem();
        pengeluaranData = new javax.swing.JMenuItem();
        kategoriData = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        tripReport = new javax.swing.JMenuItem();
        pengeluaranReport = new javax.swing.JMenuItem();
        kategoriReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setText("Selamat Datang!");

        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Data");

        tripData.setText("Trip");
        tripData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tripDataActionPerformed(evt);
            }
        });
        jMenu1.add(tripData);

        pengeluaranData.setText("Pengeluaran");
        pengeluaranData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaranDataActionPerformed(evt);
            }
        });
        jMenu1.add(pengeluaranData);

        kategoriData.setText("Kategori");
        jMenu1.add(kategoriData);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Report");

        tripReport.setText("Trip");
        jMenu2.add(tripReport);

        pengeluaranReport.setText("Pengeluaran");
        jMenu2.add(pengeluaranReport);

        kategoriReport.setText("Kategori");
        jMenu2.add(kategoriReport);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(logoutButton)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Berhasil Logout!");
        
        dispose();
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void tripDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tripDataActionPerformed
        // TODO add your handling code here:
        TripFrame frame = new TripFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_tripDataActionPerformed

    private void pengeluaranDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaranDataActionPerformed
        // TODO add your handling code here:
        PengeluaranFrame frame = new PengeluaranFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_pengeluaranDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem kategoriData;
    private javax.swing.JMenuItem kategoriReport;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenuItem pengeluaranData;
    private javax.swing.JMenuItem pengeluaranReport;
    private javax.swing.JMenuItem tripData;
    private javax.swing.JMenuItem tripReport;
    // End of variables declaration//GEN-END:variables
}
